def my_func():
    my_var = 'some text'
    print(my_var)
my_func()
#ошибка была в том, что переменная задана внутри функции, а вызывали её снаружи